export const VideoData = [
	{
		name: 'The Last Luke',
		synopsis:
			'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Consectetur excepturi aliquid distinctio eligendi, quia corrupti quidem doloremque nisi magnam ratione officia enim aliquam recusandae. Sit enim cumque in exercitationem laborum. Quas, minus deserunt quaerat dolorem mollitia ea doloribus quae animi, enim reprehenderit ab vitae debitis quod facilis possimus provident voluptas. Labore odit, autem officiis consequatur expedita debitis tempora asperiores hic. Omnis neque dignissimos quaerat, deleniti delectus quidem alias fuga ipsa eum blanditiis, eius dolorem iste doloremque eveniet. Maiores ex eligendi voluptatem quisquam quaerat minima magni veniam! Fugiat possimus magnam placeat. Possimus labore consequatur placeat enim, voluptatem quam similique unde quos iste maiores omnis nemo aliquid assumenda nostrum magnam veniam fugiat dolores totam officiis perspiciatis eum praesentium. Consequuntur tempore alias est. Inventore natus vel magnam in quod laudantium ratione nulla quidem tempore! Voluptatem quae aut, necessitatibus maiores consequuntur voluptatibus laboriosam sed, velit, neque nulla ratione iure voluptates nam hic molestiae culpa. Vitae voluptatum quis sapiente aperiam magni aliquam nihil? Explicabo ducimus ratione praesentium. Consequatur praesentium iure magni aliquid sit reiciendis, sint officiis iste! Dicta sequi labore commodi explicabo obcaecati nulla doloribus. Omnis qui consequatur a sint numquam perspiciatis distinctio possimus ab consequuntur atque inventore at, aliquam quos sapiente repellat vero harum aperiam, natus commodi provident? Quasi quaerat labore culpa temporibus ipsam? Doloremque ullam odio, a aliquid ab consequuntur tempore qui quibusdam ut suscipit aliquam. Mollitia facere animi fugiat rem natus repellat, omnis officia aliquid quod recusandae reprehenderit possimus doloribus ducimus ab! Nulla dolorem, temporibus neque quibusdam vel obcaecati accusamus earum deleniti beatae nam ab similique provident. Adipisci accusamus repellat debitis enim non, omnis cupiditate consectetur id maxime ab repellendus illum tempore. Provident illum sint, consequatur aut nisi culpa nam sunt optio? Ad ducimus exercitationem, nulla cum quae harum, sit nam perspiciatis error voluptas aspernatur, laborum eius optio voluptatem rerum incidunt nobis!',
		link: 'https://youtu.be/-Qt9i-vAPW8',
		images: [
			'https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcRv084ksxUc5GQhCvOXh2ECSKEnII6YalORoY4ZXpBPK_CHrvuJMEdIo2MVxBqPG7rIOoaphuul5etpRYL9VyJT8w',
			'https://assets-au-01.kc-usercontent.com/ab37095e-a9cb-025f-8a0d-c6d89400e446/17d49270-1b2a-4511-80a8-1c5dbd41e8c8/article-cat-vet-visit-guide.jpg'
		],
		contribution:
			'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Consectetur excepturi aliquid distinctio eligendi, quia corrupti quidem doloremque nisi magnam ratione officia enim aliquam recusandae. Sit enim cumque in exercitationem laborum. Quas, minus deserunt quaerat dolorem mollitia ea doloribus quae animi, enim reprehenderit ab vitae debitis quod facilis possimus provident voluptas. Labore odit, autem officiis consequatur expedita debitis tempora asperiores hic. Omnis neque dignissimos quaerat, deleniti delectus quidem alias fuga ipsa eum blanditiis, eius dolorem iste doloremque eveniet. Maiores ex eligendi voluptatem quisquam quaerat minima magni veniam! Fugiat possimus magnam placeat. Possimus labore consequatur placeat enim, voluptatem quam similique unde quos iste maiores omnis nemo aliquid assumenda nostrum magnam veniam fugiat dolores totam officiis perspiciatis eum praesentium. Consequuntur tempore alias est. Inventore natus vel magnam in quod laudantium ratione nulla quidem tempore! Voluptatem quae aut, necessitatibus maiores consequuntur voluptatibus laboriosam sed, velit, neque nulla ratione iure voluptates nam hic molestiae culpa. Vitae voluptatum quis sapiente aperiam magni aliquam nihil? Explicabo ducimus ratione praesentium. Consequatur praesentium iure magni aliquid sit reiciendis, sint officiis iste! Dicta sequi labore commodi explicabo obcaecati nulla doloribus. Omnis qui consequatur a sint numquam perspiciatis distinctio possimus ab consequuntur atque inventore at, aliquam quos sapiente repellat vero harum aperiam, natus commodi provident? Quasi quaerat labore culpa temporibus ipsam? Doloremque ullam odio, a aliquid ab consequuntur tempore qui quibusdam ut suscipit aliquam. Mollitia facere animi fugiat rem natus repellat, omnis officia aliquid quod recusandae reprehenderit possimus doloribus ducimus ab! Nulla dolorem, temporibus neque quibusdam vel obcaecati accusamus earum deleniti beatae nam ab similique provident. Adipisci accusamus repellat debitis enim non, omnis cupiditate consectetur id maxime ab repellendus illum tempore. Provident illum sint, consequatur aut nisi culpa nam sunt optio? Ad ducimus exercitationem, nulla cum quae harum, sit nam perspiciatis error voluptas aspernatur, laborum eius optio voluptatem rerum incidunt nobis!'
	},
	{
		name: '',
		synopsis: '',
		link: '',
		images: [''],
		contribution: ''
	}
];
