name = "anaw-portofolio"

compatibility_date = "2025-01-23"
compatibility_flags = ["nodejs_compat"]

main = ".svelte-kit/cloudflare/_worker.js"

[build]
command = "npm run build"

[env.production]
NODE_VERSION = "22.13.1"

[site]
bucket = ".svelte-kit/cloudflare"